name: CI

on:
  push:
    branches:
      - master
  pull_request:

env:
  CI: true

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      versions: >-
        ["3.3.1", "2.93.9"]
        
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Upload addon artifacts
        uses: actions/upload-artifact@v3
        with:
          name: io_hubs_addon
          path: addons
          if-no-files-found: error
